### ISSUE TITLE
combined forces

### ISSUE THREAD

**Issue by bensinober** [PTFS-Europe/docker-koha-dev#3]
Hi,
We notice you have borrowed extensively from our project, which is of course very good!
https://github.com/digibib/koha-salt-docker
branch kohadev does much of what you seek to attain
there is also:
https://github.com/digibib/kohadevbox

It seems however ideal to join forces on this one and provide one "ratified" Koha devbox for the community? For this Docker is absolutely perfect! I'm even willing to let go of my urge to use Saltstack provisioner if that feels overkill.

What say you?
Benjamin, Oslo Public Library

**Comment by mrenvoize** [comment]
Sorry Benjamin, I'd been meaning to get alex to reply to this for weeks.. We're crazy busy here at the moment but it would be great to collaborate as time permits.. Hopefully alex caught you at hackfest this week.

**Comment by bensinober** [comment]
No prob!
We talked at Hackfest and definitely have common interests. My colleague also demoed docker in production wednesday, I suppose more would be interested by now.

**Comment by a-sassmannshausen** [comment]
Hey Martin, Benjamin,

Indeed, we had some lovely conversations about this and the day Benjamin
left there was also akafred's presentation on the (impressive) docker
setup at Oslo library.

It'd be awesome to have a general koha container that we can build upon.

More specifically:

> branch kohadev does much of what you seek to attain there is also:
> https://github.com/digibib/kohadevbox

Sounds good — the benefit of this one is obviously that it uses vagrant
(rather than docker right?), so it would work on non-GNU\Linux envs.

I shall have a play with this one.

> It seems however ideal to join forces on this one and provide one
> "ratified" Koha devbox for the community? For this Docker is absolutely
> perfect! I'm even willing to let go of my urge to use Saltstack
> provisioner if that feels overkill.

I'm happy to go either way.  My personal use-case is docker for
development (I think the devbox provides a "patch" feature in the
Makefile to set up a patch environment in a specific devbox — I love
that!).

My experience for using docker in this context (dev) is the problem
which you mentioned in person: that the container carries around the
entire Git repo, thus being massive.  I liked your hack with using a
shallow clone.  It'd be interesting to see how that plays with applying
patches etc.

Other than this, I've also found the web installation procedure a pain.
Again, your mechanize script provides a nice solution.  Alternatively, I
think the devbox takes a different approach.  Either way, the problem
seems solved.

My personal feeling would be to avoid salt-provisioning, simply because
it feels like we're throwing together too many tools unnecessarily
(making the learning curve etc. steeper).  But I'm willing to be
persuaded :-)

Good to chat in person!

Alex

**Comment by a-sassmannshausen** [comment]
Haha, we're all writing at the same time :-)
